### PR TITLE
print detailed SDK errors for KMS and SSM

### LINKED ISSUE #661: tough kms errors are extremely cryptic
For any error coming from the Rust SDK, the error messages are truncated to borderline uselessness:
```
$ tuftool root add-key 99.root.json -k aws-kms://my-key-account/alias/foo -r root
Unable to parse keypair: Failed to get public key for aws-kms://my-key-account/alias/foo : service error
Unable to parse keypair: Failed to get public key for aws-kms://my-key-account/alias/foo : failed to construct request
```

The first one is a permissions error and I think the second one is a malformed `~/.aws/config`, but this is pretty challenging to debug.

Using `.into_service_error()` on the SDK error should give a more useful message.

### PR DESCRIPTION
**Pull request by bcressey**
**Issue #, if available:**
Fixes #661 

**Description of changes:**
Call `Error::source` on SDK errors to print more details about the underlying cause.

**Testing:**
Before:
```
$ tuftool root add-key 99.root.json -k aws-kms://my-key-account/alias/foo -r root
Unable to parse keypair: Failed to get public key for aws-kms://my-key-account/alias/foo : failed to construct request
```

After:
```
$ tuftool root add-key 99.root.json -k aws-kms://my-key-account/alias/foo -r root
Unable to parse keypair: Failed to get public key for aws-kms://my-key-account/alias/foo : failed to load credentials from the credentials cache
```

**Terms of contribution:**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: tough-kms/src/error.rs [hunk 1]
```diff
@@ -31,7 +32,7 @@ pub enum Error {
     "Failed to get public key for aws-kms://{}/{} : {}",
     profile.as_deref().unwrap_or(""),
     key_id,
-    source,
+    source.source().map(|x| x.to_string()).unwrap_or("unknown".to_string()),
```
Comment (stmcginnis) [inline tough-kms/src/error.rs]: Clippy wants this to be:

```
source.source().map_or("unknown".to_string(), std::string::ToString::to_string)
```

**Review by etungsten — APPROVED** [review]
LGTM after clippy fix

**Review by cbgbt — APPROVED** [review]

**Review by cbgbt — APPROVED** [review]

**Review by stmcginnis — APPROVED** [review]

**Review by webern — APPROVED** [review]
