### PR TITLE
fix(lint): Fix clippy warnings.

### LINKED ISSUE #369: clippy acronym warnings
```
 error: name `RSA` contains a capitalized acronym
   --> tough/src/sign.rs:111:5
    |
111 |     RSA(RsaKeyPair),
    |     ^^^ help: consider making the acronym lowercase, except the initial letter: `Rsa`
    |
    = note: `-D clippy::upper-case-acronyms` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#upper_case_acronyms

error: name `ED25519` contains a capitalized acronym
   --> tough/src/sign.rs:113:5
    |
113 |     ED25519(Ed25519KeyPair),
    |     ^^^^^^^ help: consider making the acronym lowercase, except the initial letter: `Ed25519`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#upper_case_acronyms

error: name `ECDSA` contains a capitalized acronym
   --> tough/src/sign.rs:115:5
    |
115 |     ECDSA(EcdsaKeyPair),
    |     ^^^^^ help: consider making the acronym lowercase, except the initial letter: `Ecdsa`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#upper_case_acronyms

error: aborting due to 3 previous errors
```

### PR DESCRIPTION
**Pull request by morenol**
*Issue #, if available:*

https://github.com/awslabs/tough/issues/369

*Description of changes:*

Fixes the clippy warnings that are currently being triggered in the develop branch.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: tough/src/sign.rs [hunk 1]
```diff
@@ -106,6 +106,7 @@ impl Sign for EcdsaKeyPair {
 
 /// Keypair used for signing metadata
 #[derive(Debug)]
+#[allow(clippy::upper_case_acronyms)]
```
Comment (morenol) [inline tough/src/sign.rs:109]: Please let me know if you like this approach or if instead it would be better to change the variants of this enum to do not use uppercase acronyms (I guess that we would need to add an entry in the Changelog in that case)

File: tough/src/schema/spki.rs [hunk 2]
```diff
@@ -125,8 +125,7 @@ fn asn1_encode_len(n: usize) -> Vec<u8> {
 /// Encode an object identifier in ASN.1.
 #[allow(clippy::cast_possible_truncation)]
 fn asn1_encode_oid(oid: &[u64]) -> Vec<u8> {
-    let mut v = Vec::new();
-    v.push((oid.get(0).unwrap_or(&0) * 40 + oid.get(1).unwrap_or(&0)) as u8);
+    let mut v = vec![((oid.get(0).unwrap_or(&0) * 40 + oid.get(1).unwrap_or(&0)) as u8)];
```
Comment (tjkirch) [inline tough/src/schema/spki.rs]:
```suggestion
    let mut v = vec![(oid.get(0).unwrap_or(&0) * 40 + oid.get(1).unwrap_or(&0)) as u8];
```
I have to admit this one confused me at first!  I don't think about single-element tuples much, so I thought this was creating one, but without a trailing comma it's just a parenthetical expression.  Rust (rustc/rustfmt/clippy) apparently allows one set of extra parens, but any more are trimmed down to one (still extra) set, probably to allow for the programmer to clarify expressions as needed but not go overboard.  In any case, this one isn't needed, and I think it's clearer to avoid it so the reader doesn't make unnecessary associations with tuples.

**Review by tjkirch — APPROVED** [review]
Thanks for your help @morenol!

**Review by tjkirch — APPROVED** [review]
